{% set name = "rush" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/rush/archive/v{{ version }}.tar.gz
  sha256: 5587a187056a3852eb910e3ce24bda7442c1997b0cf67022363b751d8cf4cdfb

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rush --help

about:
  home: https://github.com/shenwei356/rush
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A cross-platform command-line tool for executing jobs in parallel

extra:
  recipe-maintainers:
    - shenwei356
    - apcamargo
