{% set name = "rush" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/rush/archive/v{{ version }}.tar.gz
  sha256: 5f38d11af5ab8f3a9cc2c2d30f735bf6372276eba30e27530aa2393986f82a26

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rush --help

about:
  home: https://github.com/shenwei356/rush
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A cross-platform command-line tool for executing jobs in parallel

extra:
  recipe-maintainers:
    - shenwei356
    - apcamargo
