{% set name = "rush" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/rush/archive/v{{ version }}.tar.gz
  sha256: d8d04a4fd506a2f369ec8753b339364cd7e58749f794d60cf2cbbb2a5833c8ec

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rush --help

about:
  home: https://github.com/shenwei356/rush
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A cross-platform command-line tool for executing jobs in parallel

extra:
  recipe-maintainers:
    - shenwei356
    - apcamargo
